# Pull base image from https://hub.docker.com/_/python/
FROM nikolaik/python-nodejs:python3.6-nodejs10

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Add Backend
ADD ./backend /backend/
WORKDIR /backend
RUN pip install -r requirements.txt

# Add frontend 
ADD ./frontend /frontend/
WORKDIR /frontend
# Build production-ready frontend and serve it through Django
RUN npm install && npm run build 
RUN cp -r build /backend/backend/static
# Remove un-built frontend
RUN rm -rf /frontend

WORKDIR /backend

ENV ENVIRONMENT="dev"

EXPOSE 8000

ENTRYPOINT ["python", "manage.py", "runserver", "0.0.0.0:8000"]
